package com.burpmcp.ultra.core

import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Guards the single-sourced version. [BuildInfo] is generated by Gradle from the
 * project `version` (build.gradle.kts), so every runtime reference (UI tab, dashboard,
 * MCP server identity) stays in sync and cannot drift like the old hardcoded
 * dashboard "v2.0" label did.
 */
class BuildInfoTest {

    @Test
    fun `VERSION is a non-blank semver string`() {
        assertTrue(BuildInfo.VERSION.isNotBlank(), "BuildInfo.VERSION is blank")
        assertTrue(
            BuildInfo.VERSION.matches(Regex("""\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?""")),
            "BuildInfo.VERSION is not semver: '${BuildInfo.VERSION}'"
        )
    }
}
