#!/usr/bin/env python3
"""Regenerate docs/tools.md from the tool definitions in src/main/kotlin.

The descriptions embedded in tools/**.kt are the same strings the MCP server
advertises to agents at runtime; this script mirrors them into an offline
reference. Run from the repo root after changing any tool schema:

    python3 scripts/gen_tool_docs.py
"""
import re, os, glob
from collections import OrderedDict

TOOLS_GLOB = 'src/main/kotlin/com/burpmcp/ultra/tools/**/*.kt'
OUT = 'docs/tools.md'

TITLES = {
 'ProxyTools':('Proxy','proxy'), 'HttpTools':('HTTP','http'), 'ScannerTools':('Scanner','scanner'),
 'CollaboratorTools':('Collaborator','collaborator'), 'IntruderTools':('Intruder','intruder'),
 'RepeaterTools':('Repeater','repeater'), 'SitemapTools':('Sitemap','sitemap'),
 'ScopeTools':('Scope','scope'), 'ComparerTools':('Comparer','comparer'),
 'DecoderTools':('Decoder','decoder'), 'OrganizerTools':('Organizer','organizer'),
 'WebSocketTools':('WebSocket','websocket'), 'BurpSuiteTools':('Burp Suite','burp-suite'),
 'UtilitiesTools':('Utilities','utilities'), 'AiTools':('Burp AI','burp-ai'),
 'BambdaTools':('Bambda','bambda'), 'PersistenceTools':('Persistence & Preferences','persistence--preferences'),
 'ProjectTools':('Project','project'), 'LoggingTools':('Logging','logging'),
 'EventsTools':('Events','events'), 'AnalysisTools':('Analysis','analysis'),
 'ConfigTools':('Config','config'), 'SessionTools':('Session Handling','session-handling'),
 'ExtensionTools':('Extension','extension'), 'BCheckTools':('BCheck','bcheck'),
 'ScanCheckTools':('Scan Checks (script)','scan-checks-script'),
 'AuthDiffTools':('Auth Diff','auth-diff'), 'ApiImportTools':('API Import','api-import'),
 'PassiveIntelTools':('Passive Intel','passive-intel'), 'JwtTools':('JWT','jwt'),
 'FindingsTools':('Findings','findings'), 'ReconTools':('Recon','recon'),
 'GraphQlTools':('GraphQL','graphql'), 'WebProbeTools':('Web Probe (CORS & fingerprint)','web-probe'),
 'AccessControlTools':('Access Control','access-control'), 'InjectionTools':('Injection Probe','injection-probe'),
 'IdorTools':('IDOR Hunt','idor-hunt'), 'IdentityTools':('Identity Matrix','identity-matrix'),
}

groups = OrderedDict()
for path in sorted(glob.glob(TOOLS_GLOB, recursive=True)):
    src = open(path).read()
    for m in re.finditer(r'name\s*=\s*"([a-z_0-9]+)"', src):
        window = src[max(0, m.start()-200): m.start()+6000]
        dm = re.search(r'description\s*=\s*("""(?:.|\n)*?"""|"(?:[^"\\]|\\.)*"(?:\s*\+\s*\n?\s*"(?:[^"\\]|\\.)*")*)', window)
        desc = ''
        if dm:
            d = dm.group(1)
            desc = d[3:-3] if d.startswith('"""') else ''.join(re.findall(r'"((?:[^"\\]|\\.)*)"', d))
            desc = desc.replace('\r','').replace('\\"','"').replace('\\n','\n')
        groups.setdefault(os.path.basename(path)[:-3], []).append({'name': m.group(1), 'desc': desc.strip()})

total = sum(len(v) for v in groups.values())
out = [f"<!-- GENERATED by scripts/gen_tool_docs.py — do not edit by hand;",
       "     descriptions are the same strings the MCP server advertises to the",
       "     agent, so this file is the offline mirror of the live tool list. -->",
       "", "# Tool Reference", "", f"{total} MCP tools across {len(groups)} classes.",
       "Each tool documents what the agent sends and what comes back, in the same",
       "wording the MCP server advertises at runtime.", ""]
for f, tools in groups.items():
    title, _ = TITLES.get(f, (f, f.lower()))
    out.append(f"\n## {title} ({len(tools)})\n")
    for t in tools:
        out.append(f"### `{t['name']}`\n")
        out.append(re.sub(r'\n{3,}', '\n\n', t['desc']).strip() + "\n")

open(OUT, 'w').write('\n'.join(out))
print(f"{OUT}: {total} tools, {len(groups)} classes")
